version: "3.7"

services:
    app:
        container_name: app_overdrive
        build:
            args:
                user: gestaobytes
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app #laravel9
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - backend_overdrive

    nginx:
        container_name: nginx_overdrive
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8955:80
            - 4455:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - backend_overdrive

    mysql:
        container_name: mysql_overdrive
        image: mysql/mysql-server:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33060:3306
        networks:
            - backend_overdrive

    postgres:
        container_name: postgres_overdrive
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            # - 33060:3306
            - 5432:5432
        networks:
            - backend_overdrive

    redis:
        container_name: redis_overdrive
        image: redis:latest
        networks:
            - backend_overdrive

networks:
    backend_overdrive:
        driver: bridge
